//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameStats.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GameStatsDbEntities : DbContext
    {
        public GameStatsDbEntities()
            : base("name=GameStatsDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CATEGORY> CATEGORY { get; set; }
        public virtual DbSet<GAME> GAME { get; set; }
        public virtual DbSet<GAME_CATEGORY> GAME_CATEGORY { get; set; }
        public virtual DbSet<HUMAN> HUMAN { get; set; }
    }
}
