//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameStats.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class GAME_CATEGORY
    {
        public int ID { get; set; }
        public int CATEGORY_ID { get; set; }
        public int GAME_ID { get; set; }
    
        public virtual CATEGORY CATEGORY { get; set; }
        public virtual GAME GAME { get; set; }
    }
}
